navikt/fpfordel

domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/OpprettGSakOppgaveTask.java, domene/src/main/java/no/nav/foreldrepenger/mottak/felles/MottakMeldingDataWrapper.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/HentOgVurderInfotrygdSakTask.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/KlargjorForVLTask.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/OverførTilGsakFeilhåndteringsalgoritme.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/TilJournalføringTask.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/VedlikeholdSchedulerTask.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/dokumentforsendelse/BehandleDokumentforsendelseTask.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTask.java, domene/src/main/java/no/nav/foreldrepenger/mottak/tjeneste/HentDataFraJoarkTjeneste.java, domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjenesteTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/OpprettGSakOppgaveTjenesteTaskTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/journal/JournalTjenesteUtilTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/klient/FagsakRestKlientImplTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/task/HentOgVurderVLSakTaskTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/task/MidlJournalføringTaskTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/task/TilJournalføringTaskTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/tjeneste/KlargjørForVLTjenesteTest.java
Det er vel mange eldre barn som har diskresjonskode. 
Vil ikke ha unødvendige journalføringsoppgaver på enheten.
=> TFP-2966 sjekk kun bruker og 2part ved vurdering av Vikafossen

domene/pom.xml, pom.xml
=> bumped kontrakter for å få med nye felt

web/src/main/java/no/nav/foreldrepenger/fordel/dokument/v1/BehandleDokumentService.java, web/src/test/java/no/nav/foreldrepenger/fordel/dokument/v1/BehandleDokumentServiceTest.java
Unngå å få ES-søknad inn på henlagt FP-sak v/journalføring fra Gosys
=> TFP-3217 sperrre for kryssjournalføring

migreringer/src/main/resources/db/migration/defaultDS/3.0/V3.0_07__fersk-prosesstask.sql, nais/dev-fss-q1.json, nais/prod-fss-default.json, pom.xml, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/ForvaltningRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/konfig/RestApiAbacTest.java
Det måtte til litt fiksing av partisjon for å kjøre riktig når man migrerer eksisterende.
=> NOJIRA oppgrader felles og prosesstask

domene/pom.xml, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/journal/ArkivTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/person/GeoTilknytning.java, domene/src/main/java/no/nav/foreldrepenger/mottak/person/PersonTjeneste.java, domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjenesteTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/journal/ArkivTjenesteTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/task/MidlJournalføringTaskTest.java, nais/dev-fss-teamforeldrepenger.json, nais/prod-fss-teamforeldrepenger.json, pom.xml
Ny felles + PDL/person sammenlign+logg
=> NOJIRA ny felles og pdl

nais/dev-fss-teamforeldrepenger.json, nais/prod-fss-teamforeldrepenger.json, web/es-vtp.properties
De flytter vekk fra default til teamns. Dev om noen dager. Prod ukjent tidspunkt.
=> NOJIRA til ingress mens oppgave flytter til teamns

domene/src/main/java/no/nav/foreldrepenger/mottak/hendelse/JournalføringHendelseHåndterer.java, domene/src/main/java/no/nav/foreldrepenger/mottak/hendelse/JournalføringHendelseStream.java
Første steg for å studere forekomst og om/hvordan disse journalpostene skal håndteres
=> NOJIRA logge forekomster av tema endret

nais/dev-fss-teamforeldrepenger.json, web/pom.xml, web/src/main/java/no/nav/foreldrepenger/fordel/dokument/v1/BehandleDokumentService.java, web/src/test/java/no/nav/foreldrepenger/fordel/dokument/v1/BehandleDokumentServiceTest.java, web/src/test/resources/application-local.properties
Midlertidig tiltak for å redusere kompleksiteten i prodsetting. Slippe streng synkronisering
Gosys kan sende arkivsaksnummer selv om vi har et fagsakNr - prøver finne et fagsakNr før vi gir opp
=> NOJIRA støtte gammel kovensjon for å redusere kompleksitet

domene/src/main/java/no/nav/foreldrepenger/mottak/journal/ArkivTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/TilJournalføringTask.java, domene/src/test/java/no/nav/foreldrepenger/mottak/task/TilJournalføringTaskTest.java, web/src/main/java/no/nav/foreldrepenger/fordel/dokument/v1/BehandleDokumentService.java, web/src/test/java/no/nav/foreldrepenger/fordel/dokument/v1/BehandleDokumentServiceTest.java
Der var det egne regler for FAGSAK ved oppdater https://confluence.adeo.no/display/BOA/oppdaterJournalpost
=> NOJIRA valideringsregel i dokarkiv fro fagsak

fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/task/dokumentforsendelse/BehandleDokumentforsendelseTask.java, fordel-domene/src/test/java/no/nav/foreldrepenger/mottak/task/dokumentforsendelse/BehandleDokumentforsendelseTaskTest.java
For å håndtere feilet task og øvrige tilfelle som roter til SVP-søknader. 
Søknaden sender rene ettersendelser som søknad -> fører til registrer papirsøknad.
=> Midlertidig tilpasning til feil doktype fra søknad svp

fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTask.java, fordel-web/pom.xml, fordel-web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/ForvaltningRestTjeneste.java, fordel-web/src/main/java/no/nav/foreldrepenger/fordel/web/server/jetty/TokenSupportTokenProvider.java, fordel-web/src/test/resources/application-local.properties, pom.xml
Felles 3.2.31
Oppsett for lokal kjøring og lokal bruk av swagger
Par forbedringer i håndtering av avvikende journalposter
=> Ny felles og oppsett for lokal kjøring

fordel-domene/src/test/java/no/nav/foreldrepenger/mottak/tjeneste/dokumentforsendelse/DokumentforsendelseTjenesteImplTest.java
Dette er eneste prosjektet som bruker noen av klassene i den modulen ....
=> Forberede fjerning av felles-sikkherhet-testutilities

fordel-domene/src/test/java/no/nav/foreldrepenger/mottak/tjeneste/dokumentforsendelse/DokumentforsendelseTjenesteImplTest.java
=> Revert "Forberede fjerning av felles-sikkherhet-testutilities"

.github/workflows/build-pr.yml, .github/workflows/build.yml, .github/workflows/promote.yml
=> Revert "Bump actions/checkout from 2 to 2.3.4"

pom.xml
=> Revert "Bump resteasy.version from 4.6.0.Final to 4.6.1.Final"

fordel-web/src/main/java/no/nav/foreldrepenger/fordel/dokument/v1/BehandleDokumentService.java
Et forsøk på å gjøre viktig logikk rundt valg av saksnummer
tydeligere i koden, samt litt annen opprydning.
=> Refaktorere BehandleDokumentService

web/src/main/java/no/nav/foreldrepenger/fordel/web/server/abac/AppPepImpl.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/server/abac/AppXacmlRequestBuilderTjenesteImpl.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/server/abac/LokalPdpKlientImpl.java
Legger på tokex tokenbody til abac, setter ikke Subject-attributter.
Forsøksvis
=> Forsøk med tokenx token_body til abac, uten subject-attribs

pom.xml, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/DokumentforsendelseRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/DokumentforsendelseRestTjenesteTest.java, web/src/test/resources/application-local.properties
Går dette bra så kan den fjernes fra autotest
=> Bruke FpApplication for fpinfo-url

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjenesteTest.java
Lagt på fullstendig beskrivelse på OppgaveDto
Fjernet oppgaver uten aktør id
Fjernet JournalpostMangel da mangel på tittel er den eneste mangelen som kan oppstå
=> TFP-4124 Forbedringer oppgaverGosys

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjenesteTest.java
Dersom det blir veldig kunstig å vente 1-2s før man henter oppgaver på nytt.
=> Journalfør med belte og bukseseler

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java
Lagt midlertidig til at Kristin og Martes identer kan se alle manuelle journalføringsoppgaver i produksjon slik at vi kan verifisere ny løsning.
=> TFP-4124 Endret hentOppgaver - Gosys

domene/src/main/java/no/nav/foreldrepenger/mottak/klient/DokumentmottakKlient.java, domene/src/main/java/no/nav/foreldrepenger/mottak/klient/LosKlient.java, domene/src/main/java/no/nav/foreldrepenger/mottak/klient/TilbakekrevingKlient.java, web/src/main/resources/application.properties, web/src/test/resources/application-local.properties
Note to self: Registrere oss som azure-consumer hos navikt/dokarkiv
Gjelder fpfordel, fpformidling, fptilbake og fpsoknad-mottak
=> Prosesstask bruker azure når adaptive

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringMapper.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringMapperTest.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjenesteTest.java
Journalpost har mangler dersom en av dokumentene mangler tittel, eller om journalposten ikke har tittel og dokumenttypen for hoveddokumentet er udefinert.
=> TFP-4124 Manuell Journalføring

domene/src/main/java/no/nav/foreldrepenger/fordel/kodeverdi/DokumentTypeId.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTask.java, pom.xml, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/ForvaltningRestTjeneste.java
9 tilfelle siste 60 dager. Disse skal rett til KA.
=> Rute TR-kjennelser rett til KA

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjenesteTest.java
Fikser feil sjekk på tom liste
=> TFP-5450 manuell journalføring

domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/JournalføringsOppgave.java, domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/JournalføringsOppgaveTest.java, pom.xml
Begynner å opprette oppgaver på enhet 4867 nasjonal kø
=> Flytt første enhet til nasjonal kø

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjenesteTest.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjenesteTest.java
Lagt inn at FerdigstillJournalføringRestTjeneste returnerer et saksnummer når ferdgistilling er ferdig og ok.
=> TFP-5458 manuell journalføring

web/src/main/resources/application-dev-fss.properties
Den siste som sto igjen. Har søkt gjennom alle repos
=> Rett ingress til gcp

pom.xml
=> Revert "Bump kafka-streams-avro-serde from 7.3.3 to 7.4.0"

domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/JournalføringsOppgave.java, domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/JournalføringsOppgaveTest.java
=> Nasjonalisere resterende enheter

domene/src/main/java/no/nav/foreldrepenger/fordel/kodeverdi/MapNAVSkjemaDokumentTypeId.java, domene/src/main/java/no/nav/foreldrepenger/fordel/kodeverdi/NAVSkjema.java, domene/src/main/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTask.java
Det har dukket opp noen av disse i loggene. Går til manuell journalføring når de ikke er gjenkjent
=> Nye navskjema i kodeverket

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjenesteTest.java
Brukes ikke lenger aktivt av frontend https://github.com/navikt/fp-frontend/pull/4744
Legger inn info om reservasjon som kan legges inn via gosys.
Funksjonalitet for reservering/avreservering kommer som del 2 om ikke lenge.
=> Fjerner journalpostHarMangler som ikke er relevant lenger. Legger inn info om hvem har reservert oppgaven.

.github/workflows/build.yml, domene/src/main/java/no/nav/foreldrepenger/fordel/StringUtil.java, domene/src/test/java/no/nav/foreldrepenger/fordel/StringUtilTest.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/OppgaveTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjenesteTest.java
@palfi - lagde en sjekk om brukeren har faktisk lov til å reservere/avreservere i koden. Mulig det er noe sånn dere trenger i oversikt også.
=> TFP-5481: Mulighet for reservering og avreservering av en oppgave.

pom.xml
Ikke stole på dependabot - alltid sjekk https://github.com/orgs/navikt/packages?repo_name=teamdokumenthandtering-avro-schemas 
Kommer PR i vtp
=> Siste versjon av journalhendelse

domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/lager/OppgaveRepository.java, domene/src/main/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/OpprettGSakOppgaveTask.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/ForvaltningRestTjeneste.java
Den ene klagen var opprinnelig opprettet som Gosys-oppgave, flyttet til tema BID og så tilbake til FOR.
Legger klager til Gosys og gjenbruker task for å opprette oppgave for aktuell journalpost (og slette lokal oppgave)
Alle bruker fortsatt Gosys.....
=> Klager til Gosys

domene/src/main/java/no/nav/foreldrepenger/mottak/journal/ArkivTjeneste.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjenesteTest.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjenesteTest.java
@pekern legger opp til at det sendes ned en request med opprettSak som inneholder sakstype (="GENERELL") og aktørId
=> TFP-5594 journalføring på generell sak

domene/src/main/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/OpprettGSakOppgaveTask.java
Denne kan merges og prodsettes når Generell Sak er i prod (og validert)
=> Lokale oppgaver for inntektsmeldinger

domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/lager/OppgaveEntitet.java
Glemte denne da jeg revertet til Enumerated
=> Skipp sjekk ytelsetype

domene/src/main/java/no/nav/foreldrepenger/journalføring/ManuellOpprettSakValidator.java, domene/src/test/java/no/nav/foreldrepenger/journalføring/JournalpostValideringTjenesteTest.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java
Fjerner en gammel validering pga konkret tilfelle i prod
* Fagsak til mor er lenger åpen pga far og fri utsettelse
* Færre brukere av JFR - ikke like lett å opprette som i Gosys
=> Fjerner validering på åpen fagsak

domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/Journalføringsoppgave.java, domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/lager/OppgaveRepository.java, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/LosEnheterCachedTjeneste.java, domene/src/test/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjenesteTest.java, domene/src/test/java/no/nav/foreldrepenger/journalføring/oppgave/lager/OppgaveRepositoryTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/LosEnheterCachedTjenesteTest.java, domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/SaksbehandlersEnheterTjenesteTest.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/JournalføringRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/JournalføringRestTjenesteTest.java
Jeg er noe usikker om den sjekken mot PDL er riktig og/eller nyttig.
=> Filtrer vekk Klage og skjermede enheter hvor sbh ikke har tilgang i los

domene/src/main/java/no/nav/foreldrepenger/pip/PipRepository.java, domene/src/test/java/no/nav/foreldrepenger/pip/PipRepositoryTest.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/JournalføringRestTjeneste.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/server/abac/AppAbacAttributtType.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/server/abac/AppPdpRequestBuilderImpl.java
Det virker at verken FNR eller aktør fra OPPGAVE ble evaluert mot ABAC.
=> Fix ABAC evaluering

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/JournalføringRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/JournalføringRestTjenesteTest.java
Litt mer riktig HTTP-måte å si at id ikke finnes
=> Soft return av 204 dersom journalpostId ikke finnes

domene/src/main/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/OpprettGSakOppgaveTask.java
Gosys-Fordelingsoppgave oppretter en Gosys-JFR-oppgave, Lukk oppgaven i gosys og opprett lokal oppgave (utenom KA)
=> TFP-5625 fordelingsoppgave: lukk Gosys-JFR og opprett lokal oppgave

.github/dependabot.yml, pom.xml
Denne teamdokumenthandtering-avro-schemas ble ikke fanget av dependabot (ennå)
=> Aktuell versjon av journal-skjema i Avro

pom.xml
=> Revert "Bump the interne-deps group with 8 updates"

domene/src/test/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjenesteTest.java
Ref feil https://jira.adeo.no/browse/TFP-5989
=> TFP-5973: Test på filtrering av gosys-oppgaver uten journalpostId

domene/src/main/java/no/nav/foreldrepenger/fordel/kodeverdi/DokumentTypeId.java
Kommer også PR for fpsak+innsyn
=> Legger til flere dokumenttyper for bruk i selvbetjening for ES

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/ForvaltningRestTjeneste.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/migrering/MigreringRestTjeneste.java
Om oppgaven finnes fra før blir den gjenåpnet.
=> feat(TFP-6030): Legg til Swagger for oppretting av journalføringsoppgaver for journalposter uten oppgave

domene/src/main/java/no/nav/foreldrepenger/mottak/task/SikkerhetsnettTask.java
Den kjørte OK i dev, men feilet pga gamle journalposter med brukere fra Q1 eller som er forsvunnet.
Den bør virke i prod - men vil ha ut denne først
=> TFP-6044 failsafe pga dev

domene/pom.xml, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/RutingKlient.java, domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/RutingResultat.java, domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjenesteTest.java, pom.xml, web/src/main/java/no/nav/foreldrepenger/fordel/web/server/abac/AppAbacAttributtType.java, web/src/main/java/no/nav/foreldrepenger/fordel/web/server/abac/AppPdpRequestBuilderImpl.java
Her er det ikke relevant med saksnummer.
=> TFP-5972 pdprequest-makeover
