navikt/fpfordel

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/selftest/checks/DatabaseHealthCheck.java

spør på prosess_task_type isf kodeverk. sjekket andre (native) queries

FIX helsesjekk skal ikke se på kodeverdi. sjekket andre queries

---

domene/src/main/java/no/nav/foreldrepenger/fordel/kodeverdi/DokumentTypeId.java

To nye typer i forbindelse med TFP-2958 (forsvarstjeneste og tiltak i regi av Arbeids- og velferdsetaten)

Legger til nye dokumenttyper for forsvarstjeneste og navtiltak

---

pom.xml

Skjønner ikke helt hvordan dette bygger riktig med feil GroupId men kanskje den defaulter til Parent GroupId hvis oppgitt ikke finnes.

Fikser feil groupid

---

web/pom.xml

Når dette fikser java.lang.NoClassDefFoundError: org/apache/wss4j/common/cache/WSS4JCacheUtil bør nok versjonen oppdateres i fp-felles.

Fikser commons security versjon - dette er midlertidig.

---

domene/src/main/java/no/nav/foreldrepenger/mottak/hendelse/JournalføringHendelseHåndterer.java
domene/src/main/java/no/nav/foreldrepenger/mottak/journal/ArkivTjeneste.java
domene/src/main/java/no/nav/foreldrepenger/mottak/journal/dokarkiv/model/OppdaterJournalpostRequest.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTask.java

Legger på delay ved tema-endret
Midlertidig håndtering av nye/gamle saksnummer inntil arkivet har oppdatert oss (da forsvinner arkivsak mm)
Henger sammen med PR i sak, formidling, tilbake

TFP-4096 fiks tema endret, saksnummer overgangsordning

---

fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/domene/dokument/Dokument.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/journal/ArkivTjeneste.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/journal/dokarkiv/model/OpprettJournalpostRequest.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/journal/dokarkiv/model/Tilleggsopplysning.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/klient/VurderFagsystemResultat.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/task/dokumentforsendelse/BehandleDokumentforsendelseTask.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/tjeneste/VurderVLSaker.java
fordel-domene/src/test/java/no/nav/foreldrepenger/mottak/domene/dokument/DokumentRepositoryTest.java
fordel-domene/src/test/java/no/nav/foreldrepenger/mottak/journal/dokarkiv/TestDokarkiv.java
fordel-domene/src/test/java/no/nav/foreldrepenger/mottak/task/HentOgVurderVLSakTaskTest.java
pom.xml

Mellomspill før 2 større PRs
- Legger dokumenttypeid som tilleggsopplysning på journalpost -> lettere å utlede senere
- Ny kontrakter uten prøvigjen
- Litt mer kompensasjon mens vi venter på 4125

Dokumenttype som tilleggsopplysning og 4125-komp

---

fordel-web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/ForvaltningRestTjeneste.java
pom.xml

Det ligger 4 2-4 uker gamle forsendelser i fpfordel-db. 
Dokumentene er lagret OK men det ble ikke lagret en task for å behandle dem pga midlertidig feil mot tokenX eller PDL

Forvaltningtjeneste for å behandle left-behind forsendelser

---

fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/task/SlettForsendelseTask.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/tjeneste/dokumentforsendelse/DokumentforsendelseTjeneste.java
fordel-domene/src/main/java/no/nav/foreldrepenger/mottak/tjeneste/dokumentforsendelse/DokumentforsendelseTjenesteImpl.java
fordel-domene/src/test/java/no/nav/foreldrepenger/mottak/tjeneste/dokumentforsendelse/DokumentforsendelseTjenesteImplTest.java
fordel-web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/ForvaltningRestTjeneste.java
fordel-web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/DokumentforsendelseRestTjeneste.java
fordel-web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/DokumentforsendelseRestTjenesteTest.java

Når man flytter Transactional fra Rest til Service må man passe på både robusthet og ACID-egenskaper
* Alle utgående kall til resttjenester mv gjøres før lagring (både tokendings og PDL kan feile eller time ut) 
* Gjør all mapping i Rest-laget og lagre alt i en Tx - dvs ett kall.
Kall til tokendings og PDL feiler av og til -> det lå 9 søknader fra juni-september som feilet
Rekkefølgen var lagre dokument, slå opp i PDL (og tokendings) og lagring av prosesstask. 
Eksempelfeil ved oppslag: "UnknownHostException: tokendings.prod-gcp.nais.io: Temporary failure in name resolution"
Manuell gjennomgang av tilfellene ettersom noen har sendt senere søknad som er behandlet.

ACID lagring og gjør kall til tokendings før lagring

---

.deploy/naiserator.yaml
fordel-web/src/main/java/no/nav/foreldrepenger/fordel/web/server/jetty/AbstractJettyServer.java
fordel-web/src/test/resources/application-local.properties

Fpsoknad-mottak sender ved tokenX token på alle innkommende requester ned mot fpfordel. Vi har derfor ikke lenger behov for å validere token fra loginservice/id-porten.

Fjerner loginservice som issuer fordi fpfordel mottar bare TokenX token fra selvbetjening

---

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java
web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjenesteTest.java

Lagt til at vi kun henter oppgaver fra de enhetene som saksbehandler har tilgang til. Det kan være flere så vi henter i flere omganger.
Hvilke enheter SB har tilgang til hentes fra los.

TFP-4124 Utvidelse oppgaver fra Gosys

---

domene/src/main/java/no/nav/foreldrepenger/mottak/journal/ArkivTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/OppdaterJournalpostMedTittelRequest.java
web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjenesteTest.java
web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjenesteTest.java

Lagt til et endepunkt for å oppdatere tittel på dokumenter tilhørende en journalpost. Dersom valg av nye titler fører til ny journalpost tittel returneres denne. Endepunktet tar i mot en journalpostId, og en liste av DokumentId og ny tittel.

TFP-5450 Manuell journalføring

---

domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java
pom.xml

Nye Journalføringsoppgaver Oslo og Tromsø legges til nasjonal enhet.
Merges og prodsettes ettermiddagen 28/4

Nasjonalisere Oslo og Tromsø

---

domene/src/main/java/no/nav/foreldrepenger/mottak/journal/dokarkiv/DokArkivKlient.java
domene/src/main/java/no/nav/foreldrepenger/mottak/sak/SakRestKlient.java

I NAIS sitt Kubernetes miljø ble det innført overgang fra standard namespace "default" til team namespace "team". Denne endringen påvirket også URL-ene for Kubernetes-tjenesteoppdagelse. Det ble slutt på oppretting av ressurser i default namespace den 29. september 2021.
Tidligere var en vanlig NAIS tjenesteoppdagelses-URL i Kubernetes som følger: "http://app.default/". Her refererte "default" til standardnavneområdet der tjenesten var plassert. Men nå, med innføringen av teamnavneområder, har URL-en blitt endret til "http://app.team/". Dette betyr at "team" erstatter "default" i URL-en og representerer det tilhørende teamet eller prosjektet som tjenesten tilhører.
For å lette denne overgangen ble det manuelt opprettet service redirects i default namespacet.
Vi ser at appen deres har en …

Teamdokumenthandtering url oppdatering

---

domene/src/main/java/no/nav/foreldrepenger/journalføring/ManuellOpprettSakValidator.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java

Foreslår å bruke det opprinnelige DokumentTypeId om den nye blir null eller UDEFINERT.

Fix: Endring av journalpost tittel fører til endring av dokumentType

---

domene/src/main/java/no/nav/foreldrepenger/mottak/hendelse/test/VtpKafkaAvroDeserializer.java
pom.xml

Dette virket for fpabonnent, prøver samme her.

Confluent 7.4 med utvidet VTP-mock-schemareg

---

domene/src/main/java/no/nav/foreldrepenger/mottak/domene/dokument/DokumentMetadata.java
migreringer/src/main/resources/db/migration/defaultDS/3.1/V3.1_01__TFP-5571-lokalt_oppgave_tabelle.sql
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java

Har tenkt å gjøre det likt til det som gosys bruker men så er jeg noe usikker på:
- skal vi lagre prioritet siden den alltid hardkodes til NORMAL? 
- skal vi lagre utledet behandlingType eller lagre ytelseType direkte? 
- aktivDato settes også av gosys og mulig vi kan bare droppe den (settes alltid til LocalDate.now() ved opprettese)?
- hva med Tema og Temagruppe (settes alltid til .medTemagruppe("FMLI").medTema("FOR");) - kan vi bare anta det er for lokalt hos oss?

TFP-5571: Oppretter en oppgave tabel.

---

domene/src/main/java/no/nav/foreldrepenger/journalføring/domene/JournalpostId.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/Journalføringsoppgave.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjeneste.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/domene/NyOppgave.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/domene/NyOppgaveBuilder.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/domene/Oppgave.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/domene/OppgaveBuilder.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/lager/BrukerId.java
domene/src/main/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/FlyttLokalOppgaveTilGosysTask.java
domene/src/main/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/OpprettGSakOppgaveTask.java
domene/src/main/java/no/nav/foreldrepenger/mottak/felles/MottakMeldingDataWrapper.java
domene/src/test/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjenesteTest.java
domene/src/test/java/no/nav/foreldrepenger/mottak/domene/oppgavebehandling/OpprettGSakOppgaveTjenesteTaskTest.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjeneste.java
web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/ManuellJournalføringRestTjenesteTest.java

Oppgaver til frontend har et ekstra felt "kilde" som er LOKAL eller GOSYS. tenkt brukt til å enable "Flytt til Gosys"
Endepunkt for å flytte en lokal oppgave til Gosys - slik at man kan gjøre avanserte ting vi ikke vil støtte (bytt tema, ....)

TFP-5595 backend-støtte for å flytte en lokal oppgave til Gosys

---

domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/lager/OppgaveEntitet.java

Generelle papirdokument (udefinert, annet, ....) har som regel ikke behandlingstema -> ytelsetype = null

Takle udefinert ytelse for generell dokument

---

domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjeneste.java
domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/LosEnheterCachedTjeneste.java

Interessant WELD feature - om man kun bruker en Interface av en tjeneste så er det ikke nyttig at selve implementasjonen har en no-arg konstruktor definert. Se `PersonTjeneste` eller `OppgaverTjeneste`. Her brukes det `PersonInformasjon` og `Journalføringsoppgave` interfaces og da er np-arg ctor ikke nytt mens de andre tjenesten som ikke benytter et interface må definere en no-arg ctor til å virker korrekt.

Trenger en no-arg-ctor om ikke en Interface er brukt.

---

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java
web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjenesteTest.java

2 fikser: returnerer saksnummer og sikrer at det opprettes ny sak (dersom input-journalpost allerede ligger på en sak)

Sikre at knyttTilAnnen sak oppretter ny sak

---

domene/src/main/java/no/nav/foreldrepenger/mottak/domene/dokument/DokumentRepository.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/SlettGamleTasksBatchTask.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/migrering/MigreringJournalpostDto.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/migrering/MigreringMapper.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/migrering/MigreringOppgaveDto.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/migrering/MigreringRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/konfig/ApiConfig.java
web/src/test/java/no/nav/foreldrepenger/fordel/web/app/forvaltning/migrering/MigreringRestTest.java

Litt forberedelser til den tiden vi vil se på migrering til postgres.
Fordel er mer komplisert enn abonnent siden den har 2 inputs: Søknad/Rest og Kafka.
Tenker vi først deployer den uten kafka-lesing, så en deploy uten rest-mottak (exception) som kjører 10-20s (hente data + send inn søknader), før deploy av PG med rest u/kafka. Last opp data hentet ut. Deploy pG med kafka. 
Deploy en ORCL-versjon som heter "runoff" som er ferdig på et par timer.

Tidlig støtte for migrering postgres

---

web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java

Gjelder primært om SBH klarte å endre Journalpost tittel i Gosys men endret ikke Dokument tittel.

TFP-5791: Tillater å endre tittel om det er kun 1 dokument og den er forskjellig fra journalpost tittel.

---

domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjeneste.java

Her er noen opprettet maskinelt (typisk dokument til KA) eller manuelt (overfør til Gosys).
Ønsker skille disse i statistikk.

TFP-5890 ikke angi opprettet av enhet for maskinelle oppgaver

---

domene/src/main/java/no/nav/foreldrepenger/mottak/domene/MottattStrukturertDokument.java
domene/src/main/java/no/nav/foreldrepenger/mottak/domene/v1/Inntektsmelding.java
domene/src/main/java/no/nav/foreldrepenger/mottak/domene/v2/Inntektsmelding.java
domene/src/main/java/no/nav/foreldrepenger/mottak/domene/v3/Søknad.java
domene/src/main/java/no/nav/foreldrepenger/mottak/felles/MottakMeldingDataWrapper.java
domene/src/main/java/no/nav/foreldrepenger/mottak/journal/ArkivTjeneste.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/TilJournalføringTask.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/dokumentforsendelse/BehandleDokumentforsendelseTask.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTask.java
domene/src/test/java/no/nav/foreldrepenger/mottak/task/OpprettSakTaskTest.java
domene/src/test/java/no/nav/foreldrepenger/mottak/task/TilJournalføringTaskTest.java
domene/src/test/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTaskTest.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java
web/src/test/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjenesteTest.java

Altinn-håndteringen setter bruker (fra innhold i IM). 
Dokarkiv fjerner evt sakstilknytning satt av fp-inntektsmelding når bruker endres (også til samme bruker).
Hovedendringer
* Vil ikke oppdatere bruker for NavNo-IM. Når denne er merget kan FP-im sette Sak (men kan ikke ferdigstille)
* Sjekk: At journalposten har satt bruker / aktørId eller fnr
* Sjekk: At fnr inne i XML er samme person som bruker på journalposten
* Sjekk: At tema er satt
* Sjekk: At behandlingstema er satt på journalpost og at den stemmer med ytelse inne i XML

Behandle IM fra NavNo annerledes enn ALTINN

---

domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjeneste.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/oppgave/lager/OppgaveRepository.java
domene/src/test/java/no/nav/foreldrepenger/journalføring/oppgave/OppgaverTjenesteTest.java
domene/src/test/java/no/nav/foreldrepenger/journalføring/oppgave/lager/OppgaveRepositoryTest.java

Oppgaver som er flyttet til gosys blir liggende i listen over mulige oppgaver å velge fordi de nå har status "AAPNET" i gosys. Filtrerer bort oppgaver som har status "AAPNET" i gosys hvis tilsvarende lokale oppgave er lukket (status "FERDIGSTILT" eller "FEILREGISTRERT").

TFP-5968: Filtrerer ut oppgaver som er flyttet til gosys

---

domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java
domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/RutingKlient.java
domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/RutingResultat.java
domene/src/test/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjenesteTest.java
pom.xml

Tar inn felles 7.4.5 som kaller ny tilgangskontroll, sammenligner svar med gammel abac-kontroll og logger likhet/diff
Prøvde en stund, men hadde en skrivefeil i scope til pdl-pip-api.
Tar også inn kall til ruting-tjeneste i fptilgang som skal gi svar på fordeling av behandling til riktig enhet. Sammenligner med dagens logikk og logger avvik. Ved å sentralisere rutingtjenesten, kan vi fjerne bruken av skjermet-person-pip i fpfordel og fpsak.

Kall rutingtjeneste og sammenlign. Siste felles

---

domene/src/main/java/no/nav/foreldrepenger/mottak/behandlendeenhet/EnhetsTjeneste.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/SikkerhetsnettTask.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/sikkerhetsnett/SikkerhetsnettKlient.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/sikkerhetsnett/SikkerhetsnettResponse.java
web/src/main/resources/application.properties
web/src/test/resources/application-vtp.properties

Basert på beskrivelse pluss dokarkiv:FinnMottatteJournalposterController
Bruker Gosys for klageinstans, ellers lokal oppgave.
Begynner med daglig kjøring for debugging, går over til ukentlig når OK. Kan ta litt tid før det kommer noen løse tilfelle

TFP-6044 journalpost sikkerhetsnett

---

domene/src/main/java/no/nav/foreldrepenger/fordel/kodeverdi/DokumentTypeId.java
domene/src/main/java/no/nav/foreldrepenger/journalføring/ManuellOpprettSakValidator.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/FerdigstillJournalføringTjeneste.java

Ender opp i en et svart hull for validering - DokumentTypeId.erSøknadType(hovedDokumentType) er sann, men den klarer ikke utlede ytelse fra dokument i neste steg.
Skiller på validering for opprett ny sak (må ha førstegangssøknad) og validering for knyttTilAnnenSak (takler endringssøknad)

Mangel: fleksibelt uttak gjelder foreldrepenger

---

domene/src/main/java/no/nav/foreldrepenger/journalføring/ManuellOpprettSakValidator.java
domene/src/main/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTask.java
domene/src/main/java/no/nav/foreldrepenger/mottak/tjeneste/DestinasjonsRuter.java
domene/src/test/java/no/nav/foreldrepenger/journalføring/JournalpostValideringTjenesteTest.java
domene/src/test/java/no/nav/foreldrepenger/mottak/task/joark/HentDataFraJoarkTaskTest.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/JournalføringRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/journalføring/JournalpostDetaljerDto.java

Det aktuelle tilfellet traff if (jp.tilstand.erEndelig) og Log "Prøver å journalføre et dokument med tema".
Legger til en eksplisitt sperre mot å opprette sak basert på annet enn førstegang og inntektsmelding.

TFP-6070 hindre saksoppretting fra endelig journalført dok

---

domene/src/main/java/no/nav/foreldrepenger/fordel/kodeverdi/MottakKanal.java
migreringer/src/main/resources/db/migration/defaultDS/3.1/V3.1_02__chore_lange_mottakskanalnavn.sql

Vi mellomlagrer en del journalposter for å filtrere innkommende kafka. 
Tar med nyeste kanal-navn (Sykepenger IM-api) og tillater lengre kanalnavn.

chore: Oppdater mottakskanaler og tillat lengre navn
